apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: kekw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kekw
  template:
    metadata:
      labels:
        app: kekw
    spec:
      containers:
      - name: apps
        image: 787367675716.dkr.ecr.ap-south-1.amazonaws.com/argo:latest
        ports:
        - containerPort: 80
