apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypodrs
  labels:
    app: podrs
    tier: frontend
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
      - name: php-redis22
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      