apiVersion: v1
kind: Service
metadata:
  name: pots-service
  labels:
    name: clust-in
    igns: nbjs
spec:
  type: LoadBalancer
  selector:
    name: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80