apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname-deployment
  labels:
    deploy: dpwps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.4.1
        env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: wdpresconf
                key: MYSQL_USER
          - name: WORDPRESS_DB_USER
            valueFrom:
              configMapKeyRef:
                name: wdpresconf
                key: WORDPRESS_DB_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: wdpresconf
                key: WORDPRESS_DB_PASSWORD
          - name: WORDPRESS_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: wdpresconf
                key: WORDPRESS_DB_NAME
        ports:
        - containerPort: 8080
